
server:
  port: 8200

spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kranthikumar9160/microservices-config
          clone-on-start: true